---
services:
  voxtera-backend:
    image: voxtera-backend:v1
    environment:
      USE_CUDA: false
    ports:
      - "8000:8000"
  voxtera-frontend:
    image: voxtera-frontend:v1
    environment:
      VITE_API_ROOT_URL: "http://localhost:8000"
    ports:
      - "3000:3000"
    depends_on:
      - voxtera-backend
